/**
 * Dil tanımları.
 *
 * Kelime listeleri burada durmuyor; public/wordlists/ altından yükleniyor
 * (bkz. src/words.js). Bu dosya alfabe, klavye ve tüm metinleri tutar.
 *
 * `strings` toast/dialog mesajları, `ui` arayüz etiketleri.
 * MAX / TURNS / STREAK / WORDS yer tutucuları çalışma anında doldurulur.
 */
export const LANGUAGES = {
    "en-US": {
        name: "English",
        alphabet: "abcdefghijklmnopqrstuvwxyz",
        keyboardLayout: ["qwertyuiop", "asdfghjkl", "zxcvbnm"],
        enter: "Enter",
        strings: {
            "NOT_A_WORD": "not a valid word",
            "NOT_A_LETTER": "not a valid letter",
            "NOT_IN_DICT": "word not found in dictionary",
            "NO_MORE_GUESSES": "you ran out of guesses",
            "VICTORY": "you found the word!",
            "TOO_SHORT": "not enough letters",
            "HARD": "use the hints you already have",
            "LOADING": "loading words...",
            "LOAD_FAILED": "could not load the word list",
            "TIMEOUT": "time's up",
        },
        ui: {
            hint: "Hint",
            hintTitle: "Which hint?",
            hintCost: "COST guesses",
            hintMeaning: "Meaning",
            hintMeaningNote: "A trimmed dictionary definition — never the giveaway part",
            hintLetter: "Letter",
            hintLetterNote: "Reveals one letter in its place",
            hintWarn: "3 or fewer guesses left — take a hint and you get only 10 seconds for your last guess.",
            hintNoMeaning: "No definition found for this word.",
            hintUsed: "Hint used",
            hintTimed: "SECONDS seconds for your last guess",
            meaning: "Meaning",
            game: "Game",
            gameWordle: "Wordle",
            gameHangman: "Hangman",
            wordLength: "Word length",
            letters: "N letters",
            wrongLabel: "Wrong",
            hangmanWonBody: "Solved with WRONG wrong letters. Streak: STREAK.",
            hangmanHow: "Guess one letter at a time. Every miss draws another part of the figure — six misses and it's over.",
            kicker: "A word game",
            titleTop: "React",
            titleBottom: "Wordle",
            tagline: "Five letters, MAX tries, one warm little puzzle.",
            how: "Type a word and press Enter. After each guess the tiles tell you how close you were.",
            language: "Language",
            start: "Start game",
            guess: "Guess",
            newWord: "New word",
            right: "Right letter, right spot",
            near: "Right letter, wrong spot",
            none: "Not in the word",
            played: "Played",
            winPct: "Win rate",
            streak: "Streak",
            dict: "WORDS words in the dictionary",
            was: "The word was",
            wonKicker: "Solved",
            lostKicker: "Out of guesses",
            wonBody: "Found in TURNS of MAX. Streak: STREAK.",
            lostBody: "No luck this time — take another word for a walk.",
            again: "Play again",
            close: "Close",
        },
    },
    "tr-TR": {
        name: "Türkçe",
        alphabet: "abcçdefgğhıijklmnoöprsştuüvyzqxw",
        keyboardLayout: ["qwertyuıopğü", "asdfghjklşi", "zxcvbnmöç"],
        enter: "Giriş",
        strings: {
            "NOT_A_WORD": "geçersiz kelime",
            "NOT_A_LETTER": "geçersiz harf",
            "NOT_IN_DICT": "kelime sözlükte bulunamadı",
            "NO_MORE_GUESSES": "tahmin hakkınız doldu",
            "VICTORY": "kelimeyi buldunuz!",
            "TOO_SHORT": "harf sayısı yetersiz",
            "HARD": "bildiğin ipuçlarını kullan",
            "LOADING": "kelimeler yükleniyor...",
            "LOAD_FAILED": "kelime listesi yüklenemedi",
            "TIMEOUT": "süre doldu",
        },
        ui: {
            hint: "İpucu",
            hintTitle: "Hangi ipucu?",
            hintCost: "COST hak",
            hintMeaning: "Anlam",
            hintMeaningNote: "Sözlük tanımının kırpılmış hâli — ele veren kısmı asla yok",
            hintLetter: "Harf",
            hintLetterNote: "Yerinde bir harf açılır",
            hintWarn: "3 veya daha az hakkın kaldı — ipucu alırsan son tahmin için sadece 10 saniyen olur.",
            hintNoMeaning: "Bu kelimenin anlamı bulunamadı.",
            hintUsed: "İpucu kullanıldı",
            hintTimed: "Son tahmin için SECONDS saniyen var",
            meaning: "Anlamı",
            game: "Oyun",
            gameWordle: "Wordle",
            gameHangman: "Adam Asmaca",
            wordLength: "Kelime uzunluğu",
            letters: "N harf",
            wrongLabel: "Yanlış",
            hangmanWonBody: "WRONG yanlışla bildiniz. Seri: STREAK.",
            hangmanHow: "Tek tek harf tahmin edin. Her yanlış adamın bir parçasını çizer — altı yanlışta iş biter.",
            kicker: "Bir kelime oyunu",
            titleTop: "React",
            titleBottom: "Wordle",
            tagline: "Beş harf, MAX tahmin, sıcacık bir bulmaca.",
            how: "Bir kelime yazıp Giriş'e basın. Her tahminden sonra kutular ne kadar yaklaştığınızı söyler.",
            language: "Dil",
            start: "Oyuna başla",
            guess: "Tahmin",
            newWord: "Yeni kelime",
            right: "Doğru harf, doğru yerde",
            near: "Doğru harf, yanlış yerde",
            none: "Kelimede yok",
            played: "Oynanan",
            winPct: "Kazanma",
            streak: "Seri",
            dict: "Sözlükte WORDS kelime var",
            was: "Kelime şuydu",
            wonKicker: "Bildiniz",
            lostKicker: "Hak kalmadı",
            wonBody: "MAX tahminden TURNS tanesinde bulundu. Seri: STREAK.",
            lostBody: "Bu sefer olmadı — yeni bir kelimeye ne dersiniz?",
            again: "Tekrar oyna",
            close: "Kapat",
        },
    },
};
